const ShopActionTypes = {
  FETCH_COLLECTİONS_START: 'FETCH_COLLECTİONS_START',
  FETCH_COLLECTİONS_SUCCESS: 'FETCH_COLLECTİONS_SUCCESS',
  FETCH_COLLECTİONS_FAIL: 'FETCH_COLLECTİONS_FAIL',
};

export default ShopActionTypes;
